### PR TITLE
[New] support new config system

### PR DESCRIPTION
**Pull request by mufasa71**
Supporting eslint's new config system of eslint.

Note that the legacy config system always has require()d plugins and sharable configs, while the new system is ESM.

Thus [conditional export](https://nodejs.org/api/packages.html#conditional-exports) is great to keep compatibility.

plugin: protocol(e.g. plugin:effector/recommended) is not valid any more. Thus the new plugin doesn't have configs.

Sharable configs for the new config system are now exported as eslint-plugin-effector/all, eslint-plugin-effector/recommended, eslint-plugin-effector/scope and etc....

### CODE REVIEW

**Comment by mufasa71** [comment]
@igorkamyshev can you looks into this?

**Comment by igorkamyshev** [comment]
Hello!

Thanks for your contribution 🤗

I see its a lot of changes, I will take a closer look during next week.

**Comment by mufasa71** [comment]
Hey @igorkamyshev any chance to look into this?

**Comment by igorkamyshev** [comment]
> Hey @igorkamyshev any chance to look into this?

Yep, sorry, I'll take a look asap 🫡

**Comment by igorkamyshev** [comment]
Hello! I apologize for the late replay, I have been trying to figure out what is the point of the new config 🥲 and I am not succeeded.

I did not catch why we should introduce this change in this way. Moreover, I tried to install a package from this PR to `node_modules` and it's completely broken. Unit tests in the repo in broken as well. So, I assume it is not the final solution? 

Could you fix it and explain to me more about this change, please?

**Comment by mufasa71** [comment]
Hi, @igorkamyshev 
` "extends": ["plugin:effector/recommended", "plugin:effector/scope"]` this will stop to work in next major of eslint (or when team switch to new flat configs), most likely from `v9` and its to not backward compatible with this plugin, many people will start to install new eslint, but effector will block them to do it. I think its explained better than i can do [here](https://eslint.org/blog/2022/08/new-config-system-part-1)

Anyway this needs to be changed sooner or later. So this PR is all about supporting upcoming changes in eslint. About tests and broken node_modules, I can look further of course.

**Comment by igorkamyshev** [comment]
Let's exclude `"extends": ["plugin:effector/all"]` please? I think, it's better to do chores and a new feature in separate PRs 🙏

**Comment by mufasa71** [comment]
@igorkamyshev Please check #141 when you have time. Thanks!

**Pull request closed without merging**
